package atm_2;

import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

public class New_account extends javax.swing.JFrame {

    public New_account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mother = new javax.swing.JPanel();
        NewData = new Clases.PanelRound();
        New_user = new javax.swing.JLabel();
        New_User_Entry = new javax.swing.JTextField();
        New_pw = new javax.swing.JLabel();
        New_pw_entry = new javax.swing.JPasswordField();
        Create = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        IconBg = new Clases.PanelRound();
        Icon = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mother.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewData.setBackground(new java.awt.Color(0, 0, 0, 98));
        NewData.setRoundTopLeft(55);
        NewData.setRoundTopRight(55);

        New_user.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        New_user.setForeground(new java.awt.Color(255, 255, 255));
        New_user.setText("Usuario");

        New_User_Entry.setBackground(new java.awt.Color(204, 204, 204));
        New_User_Entry.setBorder(null);

        New_pw.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        New_pw.setForeground(new java.awt.Color(255, 255, 255));
        New_pw.setText("Contraseña");

        New_pw_entry.setBackground(new java.awt.Color(204, 204, 204));
        New_pw_entry.setBorder(null);

        Create.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Create.setText("Crear");
        Create.setBorder(null);
        Create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateMouseClicked(evt);
            }
        });
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NewDataLayout = new javax.swing.GroupLayout(NewData);
        NewData.setLayout(NewDataLayout);
        NewDataLayout.setHorizontalGroup(
            NewDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewDataLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(NewDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NewDataLayout.createSequentialGroup()
                        .addComponent(Create, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(NewDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(New_user, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(New_User_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(New_pw)
                        .addComponent(New_pw_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        NewDataLayout.setVerticalGroup(
            NewDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewDataLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(New_user)
                .addGap(12, 12, 12)
                .addComponent(New_User_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(New_pw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(New_pw_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(NewDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Create, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        Mother.add(NewData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 310, 210));

        IconBg.setBackground(new java.awt.Color(0, 0, 0, 98));
        IconBg.setRoundBottomLeft(100);
        IconBg.setRoundBottomRight(100);
        IconBg.setRoundTopLeft(100);
        IconBg.setRoundTopRight(100);

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/CreateUser (1).png"))); // NOI18N

        javax.swing.GroupLayout IconBgLayout = new javax.swing.GroupLayout(IconBg);
        IconBg.setLayout(IconBgLayout);
        IconBgLayout.setHorizontalGroup(
            IconBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconBgLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Icon)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        IconBgLayout.setVerticalGroup(
            IconBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconBgLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Icon)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Mother.add(IconBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/background-2402703_640.jpg"))); // NOI18N
        Background.setMinimumSize(new java.awt.Dimension(0, 0));
        Mother.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mother, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateActionPerformed

    private void CreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateMouseClicked
        String nuevoUsuario = New_User_Entry.getText();
        char[] nuevoPasswordChars = New_pw_entry.getPassword();
        String nuevoPassword = new String(nuevoPasswordChars);

        if (!nuevoUsuario.isEmpty() && !nuevoPassword.isEmpty()) {
            agregarNuevoUsuario(nuevoUsuario, nuevoPassword);
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un usuario y una contraseña válidos.");
        }
    }//GEN-LAST:event_CreateMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //dispose();
        Login evoke = new Login();
        evoke.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_account().setVisible(true);
            }
        });
    }
        private void agregarNuevoUsuario(String usuario, String contraseña) {
        try {
            String csvFile = "Data.csv"; // Ruta del archivo CSV

            // Abre el archivo CSV en modo escritura (true indica que se añadirá al final del archivo)
            FileWriter fw = new FileWriter(csvFile, true);
            BufferedWriter bw = new BufferedWriter(fw);

            // Escribe el nuevo registro en el archivo CSV (usuario y contraseña separados por punto y coma)
            bw.write(usuario + ";" + contraseña);
            bw.newLine(); // Agrega una nueva línea

            // Cierra el archivo CSV
            bw.close();
            fw.close();

            JOptionPane.showMessageDialog(null, "Nuevo usuario agregado con éxito.");
            dispose();
            // Limpia los campos de texto después de agregar el usuario
            New_User_Entry.setText("");
            New_pw_entry.setText("");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al agregar el nuevo usuario.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Create;
    private javax.swing.JLabel Icon;
    private Clases.PanelRound IconBg;
    private javax.swing.JPanel Mother;
    private Clases.PanelRound NewData;
    private javax.swing.JTextField New_User_Entry;
    private javax.swing.JLabel New_pw;
    private javax.swing.JPasswordField New_pw_entry;
    private javax.swing.JLabel New_user;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
